### ISSUE TITLE
Task: update pip to latest pybomwater

### ISSUE THREAD

**Issue by flightmansam** [csiro-hydroinformatics/pybomwater#4]
Currently the version of pybomwater on pip does not contain commits up to 9d120296678454a9227121cc0f930522c2add4e6 (quality code and metadata), even though the pybomwater packages have the same version number.

**Comment by fre171csiro** [comment]
Sorry will deploy to pypi soon

**Comment by fre171csiro** [comment]
Closing this after uploading the latest whl to pypi

**Comment by flightmansam** [comment]
Awesome! (Came here from MODSIM btw, fantastic package!)
