### ISSUE TITLE
Support Python 3.12

### ISSUE THREAD

**Issue by cal-andrew** [csiro-hydroinformatics/pybomwater#7]
Could you please let pybomwater be used with Python 3.12? It is the latest stable Python version.
Thanks for your work!

**Comment by fre171csiro** [comment]
Will look into it soon, just need to finish some other tasks first.

**Comment by fre171csiro** [comment]
Ok I have release the next version 0.1.2 on GitHub and pypi https://pypi.org/project/pybomwater/.  Let me know if there are any issues

**Comment by cal-andrew** [comment]
The latest release requires Python 3.12.2 specifically. Could you please change the highest supported Python version to `< 3.13` so it works with any version of Python 3.10 - 3.12?
